site_name: Desarrollo Web en Entorno Servidor
site_url: https://aitor-medrano.github.io/dwes2122
use_directory_urls: false

nav:
  - "Inicio": "index.md"
  - "1.- Arquitecturas Web": "01arquitecturas.md"
  - "2.- El lenguaje PHP": "02php.md"
  - "3.- PHP Orientado a Objetos": "03phpoo.md"
#  - "5.- Acceso a Datos": "05accesoDatos.md"
#  - "6.- Frameworks PHP - Laravel": "06frameworks.md"

theme:
  language: es
  favicon: imagenes/favicon.png
  name: "material"
  palette:
    primary: light blue
    accent: "Teal"
  font:
    text: Roboto
    code: Roboto Mono
  logo: "imagenes/logofp.png"
  features:
    - header.autohide
    - toc.integrate
    - navigation.tabs
    - navigation.top

extra:
  search:
    language: "es"
  social:
    - icon: material/twitter
      link: https://twitter.com/aitormedrano
    - icon: material/email-edit
      link: mailto:<a.medrano@edu.gva.es>
  analytics:
    provider: google
    property: G-X6D0LR7TC8

plugins:
  - search

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences
  - footnotes
  - meta
  - sane_lists
  - toc:
      permalink: true
      toc_depth: 3

copyright: 2021-2022 Aitor Medrano - Licencia CC BY-NC-SA
